version: "3.9"

services:
  db:
    image: postgres:16
    container_name: practice4-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      # Авто-инициализация схемы и данных:
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql:ro

volumes:
  dbdata:
